In [1]:
import numpy as np

In [2]:
np.__version__

'2.0.1'

# Core featrure of numpy is array

## *Operations*
* Create
* Delete
* Update

## 1. Create & Read

### *1D Array*

*Creating*

In [3]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

*Type of array*

In [4]:
type(arr1)

numpy.ndarray

*Shape of array mXn*

In [5]:
arr1.shape

(5,)

*Data type in array*

In [6]:
arr1.dtype

dtype('int64')

*Dimensions of array*

In [7]:
arr1.ndim

1

*Size*

In [8]:
arr1.size

5

### 2D Array

*Creating*

In [9]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

*Dimensions of array*

In [10]:
arr2.ndim

2

*Shape of array mXn*

In [11]:
arr2.shape

(2, 3)

*Count of elements in array*

In [12]:
arr2.size

6

### 3D Array

*Creating*

In [13]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

*Dimensions*

In [14]:
arr3.ndim

3

*Shape of array mXn*

In [15]:
arr3.shape

(2, 2, 3)

*Size number of element*

In [16]:
arr3.size

12

In [17]:
arr_3a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
arr_3a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [18]:
arr_3a.shape

(3, 2, 3)

In [19]:
arr_3a.ndim

3

In [20]:
arr_3a.size

18

## Create random array

In [21]:
randomArr = np.random.rand(3,2,3)
randomArr

array([[[0.55379851, 0.36549853, 0.44815455],
        [0.65266744, 0.10713692, 0.28103646]],

       [[0.83915864, 0.32793262, 0.62858684],
        [0.88534953, 0.62108833, 0.58166929]],

       [[0.65830359, 0.56887604, 0.44201745],
        [0.32009572, 0.08991499, 0.15689892]]])

In [22]:
randomArr.dtype

dtype('float64')

In [23]:
zeros = np.zeros((3,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [24]:
ones = np.ones((3,2,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [25]:
zeros.ndim

3

In [26]:
full = np.full((3,2,3),1)
full

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

*Accessing the elements*

In [27]:
arr_3a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [28]:
arr_3a[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
arr_3a[0][0]

array([1, 2, 3])

In [30]:
arr_3a[0][0][0]

np.int64(1)

In [31]:
arr_3a[0:2]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [32]:
arr_3a[-1]

array([[13, 14, 15],
       [16, 17, 18]])

In [33]:
arr_3a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [34]:
arr_3a[1][0][2]

np.int64(9)

In [35]:
arr_3a[1,0,2]

np.int64(9)

## Update and delete numpy arrays

In [36]:
a1 = np.random.rand(2,3,3)
a1

array([[[0.17528268, 0.78936024, 0.4527039 ],
        [0.78196395, 0.48742884, 0.90942536],
        [0.94943568, 0.33606896, 0.44552877]],

       [[0.22707098, 0.54922215, 0.65601276],
        [0.98262664, 0.78675057, 0.41182782],
        [0.87166734, 0.1423026 , 0.53578965]]])

In [37]:
a2 = np.random.rand(2,3,3)
a2

array([[[0.05654493, 0.10673695, 0.1026838 ],
        [0.89580956, 0.98703118, 0.66153486],
        [0.59261882, 0.13192521, 0.39453893]],

       [[0.02688759, 0.10193041, 0.66716433],
        [0.9934953 , 0.89230883, 0.45648517],
        [0.31372594, 0.01876595, 0.50085018]]])

## Mathematical operations

### *Addition*

In [38]:
np.add(a1,a2)

array([[[0.23182761, 0.89609718, 0.5553877 ],
        [1.67777352, 1.47446002, 1.57096021],
        [1.5420545 , 0.46799418, 0.8400677 ]],

       [[0.25395857, 0.65115256, 1.32317708],
        [1.97612194, 1.6790594 , 0.868313  ],
        [1.18539329, 0.16106856, 1.03663983]]])

### *Multiplication*

In [39]:
np.multiply(a1,a2)

array([[[0.00991135, 0.0842539 , 0.04648536],
        [0.70049079, 0.48110746, 0.60161657],
        [0.56265345, 0.04433597, 0.17577844]],

       [[0.00610539, 0.05598244, 0.43766831],
        [0.97623495, 0.70202448, 0.1879933 ],
        [0.27346466, 0.00267044, 0.26835034]]])

### *Division*

In [40]:
np.divide(a1,a2)

array([[[3.09988322, 7.39537949, 4.40871779],
        [0.87291316, 0.49383327, 1.37472025],
        [1.60210181, 2.54742028, 1.12923905]],

       [[8.44519589, 5.38820689, 0.98328512],
        [0.98906018, 0.8817021 , 0.9021713 ],
        [2.77843563, 7.58302034, 1.06976033]]])

### *Subraction*

In [41]:
np.subtract(a1,a2)

array([[[ 0.11873775,  0.68262329,  0.3500201 ],
        [-0.11384561, -0.49960234,  0.2478905 ],
        [ 0.35681686,  0.20414375,  0.05098984]],

       [[ 0.20018338,  0.44729174, -0.01115157],
        [-0.01086866, -0.10555826, -0.04465735],
        [ 0.5579414 ,  0.12353665,  0.03493947]]])

## Statical Functions

In [42]:
sqrt = np.sqrt(25)
_abs = np.abs(-2)
power = np.power(2,8)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [43]:
sqrt

np.float64(5.0)

In [44]:
_abs

np.int64(2)

In [45]:
power

np.int32(256)

In [46]:
log

np.float64(3.2188758248682006)

In [47]:
# a1
mins

np.float64(0.1423026033108783)

In [48]:
#a2
maxs

np.float64(0.993495298951231)

## Update

In [49]:
arr_3a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [50]:
arr_3a[0,0,0] = 1000005
arr_3a

array([[[1000005,       2,       3],
        [      4,       5,       6]],

       [[      7,       8,       9],
        [     10,      11,      12]],

       [[     13,      14,      15],
        [     16,      17,      18]]])

In [51]:
arr_3a.sort()
arr_3a

array([[[      2,       3, 1000005],
        [      4,       5,       6]],

       [[      7,       8,       9],
        [     10,      11,      12]],

       [[     13,      14,      15],
        [     16,      17,      18]]])

### *Reshape*

In [52]:
arr_3a.shape

(3, 2, 3)

In [53]:
# in the last place of 3 we can write -1 and python will figure it out
arr_3a_reshape = arr_3a.reshape(2,3,3)
arr_3a_reshape

array([[[      2,       3, 1000005],
        [      4,       5,       6],
        [      7,       8,       9]],

       [[     10,      11,      12],
        [     13,      14,      15],
        [     16,      17,      18]]])

In [54]:
arr_3a_reshape.shape

(2, 3, 3)

In [55]:
arr_3a_reshape.ndim

3

### Appending & Inserting

In [56]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [57]:
new_array = np.ones([3,2,3])
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [58]:
appd = np.append(zeros, new_array, axis=0)
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [59]:
appd = np.append(zeros, new_array, axis=1)
appd

array([[[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]]])

### *Insert*

In [60]:
insert_array = np.insert(zeros, 1, new_array, axis=0)
insert_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

# Delete

In [61]:
arr4 = np.random.rand(3,2,3)
arr4

array([[[0.69248466, 0.25074229, 0.0116147 ],
        [0.28156221, 0.46756334, 0.16726295]],

       [[0.70679134, 0.61918429, 0.76243521],
        [0.55419773, 0.15186877, 0.45746453]],

       [[0.87335415, 0.09233113, 0.57532724],
        [0.9505242 , 0.90441947, 0.78846103]]])

In [62]:
arr5 = np.delete(arr4,0,axis=1)
arr5

array([[[0.28156221, 0.46756334, 0.16726295]],

       [[0.55419773, 0.15186877, 0.45746453]],

       [[0.9505242 , 0.90441947, 0.78846103]]])

In [63]:
np.save('new_array', arr5)

In [64]:
np.load('new_array.npy')

array([[[0.28156221, 0.46756334, 0.16726295]],

       [[0.55419773, 0.15186877, 0.45746453]],

       [[0.9505242 , 0.90441947, 0.78846103]]])

In [65]:
x = np.ones((2,2,2,2,2,2,2,2,2,2))
x.ndim

10

In [66]:
x.shape

(2, 2, 2, 2, 2, 2, 2, 2, 2, 2)

In [67]:
x.size

1024